import {index,integer,real,sqliteTable,text,uniqueIndex} from "drizzle-orm/sqlite-core";
export const organizations=sqliteTable("organizations",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull()});
export const users=sqliteTable("users",{
 id:integer("id").primaryKey({autoIncrement:true}),
 clerkUserId:text("clerk_user_id").unique(),
 email:text("email").notNull().unique(),
 displayName:text("display_name").notNull(),
 status:text("status",{enum:["active","disabled"]}).notNull().default("active"),
 lastSyncedAt:text("last_synced_at").notNull().default(""),
});
export const memberships=sqliteTable("memberships",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 userId:integer("user_id").notNull(),
 role:text("role",{enum:["admin","lead","volunteer","auditor"]}).notNull(),
 status:text("status",{enum:["pending","active","suspended"]}).notNull().default("active"),
 canInviteUsers:integer("can_invite_users",{mode:"boolean"}).notNull().default(false),
 createdAt:text("created_at").notNull().default(""),
 updatedAt:text("updated_at").notNull().default(""),
},t=>[
 uniqueIndex("membership_organization_user").on(t.organizationId,t.userId),
 index("membership_organization_status").on(t.organizationId,t.status),
]);
export const accessAuditLog=sqliteTable("access_audit_log",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 actorUserId:integer("actor_user_id").notNull(),
 targetMembershipId:integer("target_membership_id").notNull(),
 action:text("action",{enum:["role_changed","status_changed","invitation_rights_changed","invitation_created","invitation_resent","invitation_cancelled","invitation_accepted","booth_assigned","booth_unassigned"]}).notNull(),
 beforeJson:text("before_json").notNull(),
 afterJson:text("after_json").notNull(),
 createdAt:text("created_at").notNull(),
},t=>[
 index("access_audit_organization_created").on(t.organizationId,t.createdAt),
 index("access_audit_target_membership").on(t.targetMembershipId),
]);
export const boothLifecycleAudit=sqliteTable("booth_lifecycle_audit",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 boothId:integer("booth_id").notNull(),
 actorUserId:integer("actor_user_id").notNull(),
 action:text("action",{enum:["manually_archived","alert_acknowledged","alert_muted","alert_unmuted","alert_flagged","alert_resolved"]}).notNull(),
 detailsJson:text("details_json").notNull(),
 createdAt:text("created_at").notNull(),
},t=>[
 index("booth_lifecycle_audit_org_created").on(t.organizationId,t.createdAt),
 index("booth_lifecycle_audit_booth").on(t.boothId),
]);
export const adminAlerts=sqliteTable("admin_alerts",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 boothId:integer("booth_id").notNull(),
 type:text("type",{enum:["manual_archive_with_activity"]}).notNull(),
 status:text("status",{enum:["open","acknowledged","review","resolved"]}).notNull().default("open"),
 muted:integer("muted",{mode:"boolean"}).notNull().default(false),
 acknowledgedByUserId:integer("acknowledged_by_user_id"),
 acknowledgedAt:text("acknowledged_at"),
 mutedByUserId:integer("muted_by_user_id"),
 mutedAt:text("muted_at"),
 resolutionNote:text("resolution_note"),
 createdAt:text("created_at").notNull(),
 updatedAt:text("updated_at").notNull(),
},t=>[
 index("admin_alert_org_status_created").on(t.organizationId,t.status,t.createdAt),
 index("admin_alert_booth").on(t.boothId),
]);
export const organizationInvitations=sqliteTable("organization_invitations",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 membershipId:integer("membership_id").notNull(),
 email:text("email").notNull(),
 role:text("role",{enum:["admin","lead","volunteer","auditor"]}).notNull(),
 canInviteUsers:integer("can_invite_users",{mode:"boolean"}).notNull().default(false),
 status:text("status",{enum:["pending","accepted","cancelled","expired"]}).notNull().default("pending"),
 clerkInvitationId:text("clerk_invitation_id").notNull().unique(),
 invitedByUserId:integer("invited_by_user_id").notNull(),
 createdAt:text("created_at").notNull(),
 updatedAt:text("updated_at").notNull(),
 acceptedAt:text("accepted_at"),
 cancelledAt:text("cancelled_at"),
},t=>[
 index("organization_invitation_org_status").on(t.organizationId,t.status),
 index("organization_invitation_email_status").on(t.email,t.status),
 index("organization_invitation_membership").on(t.membershipId),
]);
export const booths=sqliteTable("booths",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 name:text("name").notNull(),
 address:text("address").notNull(),
 locationName:text("location_name"),
 googlePlaceId:text("google_place_id"),
 latitude:real("latitude"),
 longitude:real("longitude"),
 startsAt:text("starts_at").notNull(),
 endsAt:text("ends_at").notNull(),
 status:text("status",{enum:["draft","scheduled","live","closed"]}).notNull().default("draft"),
 archivedAt:text("archived_at"),
 archivedByUserId:integer("archived_by_user_id"),
 archiveReason:text("archive_reason"),
 archiveKind:text("archive_kind",{enum:["manual"]}),
 scoutAssignmentRevision:text("scout_assignment_revision").notNull().default(""),
 salesRevision:integer("sales_revision").notNull().default(0),
},t=>[
 index("booth_organization_status_start").on(t.organizationId,t.status,t.startsAt),
 index("booth_google_place").on(t.googlePlaceId),
 index("booth_organization_archived").on(t.organizationId,t.archivedAt),
]);
export const assignments=sqliteTable("assignments",{
 id:integer("id").primaryKey({autoIncrement:true}),
 boothId:integer("booth_id").notNull(),
 userId:integer("user_id").notNull(),
 role:text("role",{enum:["lead","volunteer","auditor"]}).notNull(),
},t=>[
 uniqueIndex("assignment_booth_user").on(t.boothId,t.userId),
 index("assignment_user").on(t.userId),
]);
export const scouts=sqliteTable("scouts",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 name:text("name").notNull(),
 ageLevel:text("age_level",{enum:["Daisy","Brownie","Junior","Cadette","Senior","Ambassador"]}).notNull(),
 archivedAt:text("archived_at"),
 createdAt:text("created_at").notNull(),
 updatedAt:text("updated_at").notNull(),
},t=>[
 index("scout_organization_archived_name").on(t.organizationId,t.archivedAt,t.name),
]);
export const boothScoutAssignments=sqliteTable("booth_scout_assignments",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 boothId:integer("booth_id").notNull(),
 scoutId:integer("scout_id").notNull(),
 attendanceStart:text("attendance_start").notNull(),
 attendanceEnd:text("attendance_end").notNull(),
 stayedThroughClose:integer("stayed_through_close",{mode:"boolean"}).notNull().default(false),
 createdAt:text("created_at").notNull(),
 updatedAt:text("updated_at").notNull(),
},t=>[
 uniqueIndex("booth_scout_assignment_booth_scout").on(t.boothId,t.scoutId),
 index("booth_scout_assignment_organization").on(t.organizationId),
 index("booth_scout_assignment_scout").on(t.scoutId),
]);
export const scoutSalesCredits=sqliteTable("scout_sales_credits",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 boothId:integer("booth_id").notNull(),
 saleId:text("sale_id").notNull(),
 transactionId:text("transaction_id").notNull(),
 scoutId:integer("scout_id").notNull(),
 reconciliationId:integer("reconciliation_id").notNull(),
 creditNumerator:integer("credit_numerator").notNull(),
 creditDenominator:integer("credit_denominator").notNull(),
 finalizedAt:text("finalized_at").notNull(),
},t=>[
 uniqueIndex("scout_credit_transaction_scout").on(t.transactionId,t.scoutId),
 index("scout_credit_organization_scout").on(t.organizationId,t.scoutId),
 index("scout_credit_booth").on(t.boothId),
 index("scout_credit_sale").on(t.saleId),
 index("scout_credit_reconciliation").on(t.reconciliationId),
]);
export const products=sqliteTable("products",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 name:text("name").notNull(),
 barcode:text("barcode").notNull(),
 price:real("price").notNull().default(6),
 active:integer("active",{mode:"boolean"}).notNull().default(true),
 updatedAt:text("updated_at").notNull().default(""),
},t=>[
 uniqueIndex("product_barcode_org").on(t.organizationId,t.barcode),
 index("product_organization_active_name").on(t.organizationId,t.active,t.name),
]);
export const inventory=sqliteTable("inventory",{id:integer("id").primaryKey({autoIncrement:true}),boothId:integer("booth_id").notNull(),productId:integer("product_id").notNull(),opening:integer("opening").notNull(),sold:integer("sold").notNull().default(0),adjusted:integer("adjusted").notNull().default(0)},t=>[uniqueIndex("inventory_booth_product").on(t.boothId,t.productId)]);
export const inventoryConfigurationAudit=sqliteTable("inventory_configuration_audit",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 boothId:integer("booth_id").notNull(),
 actorUserId:integer("actor_user_id").notNull(),
 beforeJson:text("before_json").notNull(),
 afterJson:text("after_json").notNull(),
 createdAt:text("created_at").notNull(),
},t=>[
 index("inventory_configuration_audit_org_created").on(t.organizationId,t.createdAt),
 index("inventory_configuration_audit_booth").on(t.boothId),
]);
export const sales=sqliteTable("sales",{
 id:text("id").primaryKey(),
 boothId:integer("booth_id").notNull(),
 operatorId:integer("operator_id").notNull(),
 paymentMethod:text("payment_method",{enum:["cash","credit_card","venmo_paypal"]}).notNull(),
 boxCount:integer("box_count").notNull(),
 totalAmount:real("total_amount").notNull(),
 createdAt:text("created_at").notNull(),
},t=>[
 index("sales_booth_created").on(t.boothId,t.createdAt),
 index("sales_booth_payment").on(t.boothId,t.paymentMethod),
]);
export const saleReversals=sqliteTable("sale_reversals",{
 id:text("id").primaryKey(),
 saleId:text("sale_id").notNull().unique(),
 organizationId:integer("organization_id").notNull(),
 boothId:integer("booth_id").notNull(),
 reversedByUserId:integer("reversed_by_user_id").notNull(),
 reversedByClerkUserId:text("reversed_by_clerk_user_id").notNull(),
 reasonCode:text("reason_code",{enum:["wrong_cookies","wrong_quantity","wrong_payment_method","duplicate_sale","other"]}).notNull(),
 reasonDetail:text("reason_detail"),
 reversedAt:text("reversed_at").notNull(),
},t=>[
 index("sale_reversals_org_booth_time").on(t.organizationId,t.boothId,t.reversedAt),
]);
export const transactions=sqliteTable("transactions",{id:text("id").primaryKey(),saleId:text("sale_id"),boothId:integer("booth_id").notNull(),productId:integer("product_id").notNull(),operatorId:integer("operator_id").notNull(),type:text("type",{enum:["sale","correction","adjustment"]}).notNull(),quantity:integer("quantity").notNull(),amount:real("amount").notNull(),reason:text("reason"),createdAt:text("created_at").notNull()},t=>[index("transactions_sale").on(t.saleId)]);
export const reconciliations=sqliteTable("reconciliations",{
 id:integer("id").primaryKey({autoIncrement:true}),
 boothId:integer("booth_id").notNull().unique(),
 closedBy:integer("closed_by").notNull(),
 cashTotal:real("cash_total").notNull(),
 expectedCashTotal:real("expected_cash_total").notNull().default(0),
 cashDiscrepancy:real("cash_discrepancy").notNull().default(0),
 digitalTotal:real("digital_total").notNull(),
 creditCardTotal:real("credit_card_total").notNull().default(0),
 venmoPaypalTotal:real("venmo_paypal_total").notNull().default(0),
 grossTotal:real("gross_total").notNull().default(0),
 expectedBoxCount:integer("expected_box_count").notNull().default(0),
 actualBoxCount:integer("actual_box_count").notNull().default(0),
 inventoryDiscrepancyCount:integer("inventory_discrepancy_count").notNull().default(0),
 notes:text("notes"),
 closedAt:text("closed_at").notNull(),
 salesRevision:integer("sales_revision").notNull().default(0),
});
export const reconciliationItems=sqliteTable("reconciliation_items",{
 id:integer("id").primaryKey({autoIncrement:true}),
 reconciliationId:integer("reconciliation_id").notNull(),
 productId:integer("product_id").notNull(),
 expectedRemaining:integer("expected_remaining").notNull(),
 actualRemaining:integer("actual_remaining").notNull(),
 discrepancy:integer("discrepancy").notNull(),
 returnedToTroop:integer("returned_to_troop").notNull(),
},t=>[
 uniqueIndex("reconciliation_item_reconciliation_product").on(t.reconciliationId,t.productId),
 index("reconciliation_item_product").on(t.productId),
]);

export const productCatalogAudit=sqliteTable("product_catalog_audit",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 productId:integer("product_id").notNull(),
 actorUserId:integer("actor_user_id").notNull(),
 beforeJson:text("before_json").notNull(),
 afterJson:text("after_json").notNull(),
 createdAt:text("created_at").notNull(),
},t=>[
 index("product_catalog_audit_org_created").on(t.organizationId,t.createdAt),
 index("product_catalog_audit_product").on(t.productId),
]);

export const troopInventoryBalances=sqliteTable("troop_inventory_balances",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 productId:integer("product_id").notNull(),
 totalRemaining:integer("total_remaining").notNull().default(0),
 available:integer("available").notNull().default(0),
 updatedAt:text("updated_at").notNull(),
},t=>[
 uniqueIndex("troop_inventory_balance_org_product").on(t.organizationId,t.productId),
 index("troop_inventory_balance_org").on(t.organizationId),
]);

export const inventoryLedger=sqliteTable("inventory_ledger",{
 id:integer("id").primaryKey({autoIncrement:true}),
 organizationId:integer("organization_id").notNull(),
 productId:integer("product_id").notNull(),
 boothId:integer("booth_id"),
 actorUserId:integer("actor_user_id"),
 movementType:text("movement_type",{enum:["initial_order","replenishment","booth_allocation","booth_return","booth_sale","trade_in","trade_out","council_return","damage","loss","correction_in","correction_out","legacy_migration"]}).notNull(),
 totalDelta:integer("total_delta").notNull().default(0),
 availableDelta:integer("available_delta").notNull().default(0),
 boothDelta:integer("booth_delta").notNull().default(0),
 reason:text("reason"),
 reference:text("reference"),
 createdAt:text("created_at").notNull(),
},t=>[
 index("inventory_ledger_org_created").on(t.organizationId,t.createdAt),
 index("inventory_ledger_product_created").on(t.productId,t.createdAt),
  index("inventory_ledger_booth").on(t.boothId),
]);

export const superAdminAuditLog=sqliteTable("super_admin_audit_log",{
 id:integer("id").primaryKey({autoIncrement:true}),
 actorClerkUserId:text("actor_clerk_user_id").notNull(),
 actorUserId:integer("actor_user_id"),
 actorDisplayName:text("actor_display_name").notNull(),
 action:text("action",{enum:["organization_data_purged","organization_data_purge_failed"]}).notNull(),
 targetOrganizationId:integer("target_organization_id").notNull(),
 targetOrganizationName:text("target_organization_name").notNull(),
 reason:text("reason"),
 deletedCountsJson:text("deleted_counts_json").notNull(),
 outcome:text("outcome",{enum:["success","failure"]}).notNull(),
 requestId:text("request_id").notNull(),
 createdAt:text("created_at").notNull(),
},t=>[
 index("super_admin_audit_created").on(t.createdAt),
 index("super_admin_audit_target_created").on(t.targetOrganizationId,t.createdAt),
]);
